feat: add default tolerations and tolerations input
Altinity/terraform-altinitycloud-connect pull request #11
Opened 2024-11-08 22:15 UTC by ianaya89

2024-11-08 22:21 UTC, shyiko requested changes

2024-11-08 22:21 UTC, shyiko commented on main.tf
> +  default_toleration = [
s/default_toleration/default_tolerations

2024-11-08 22:21 UTC, shyiko commented on main.tf
> +      key      = "altinity.cloud"
"altinity.cloud/use"

2024-11-10 09:04 UTC, denisok approved these changes

2024-11-15 02:25 UTC, merged